#ifndef SYSTICK_PRV_H
#define SYSTICK_PRV_H


#define STK_CTRL_ENABLE 			0U
#define STK_CTRL_TICKINT			1U
#define STK_CTRL_CLKSOURCE 			2U
#define STK_CTRL_COUNTFLAG 			16U

#define STK_LOAD_RELOAD				 0U

#define STK_VAL_CURRENT 			0U

#define SYST_DELAY_LIMIT_US_8MHz 	16777215UL
#define SYST_MASK 					1U

#define SYST_MILLISECOUND_DIVITION_FACTROR  1000U

#define SYST_MICREOSECOUND_DIVITION_FACTROR  1000000U

#define SYST_DISABLE 0U

#endif
