/*
 * NVIC_Private.h
 *
 *  Created on: Jul 5, 2023
 *      Author: Ziyad
 */

#ifndef NVIC_PRIVATE_H_
#define NVIC_PRIVATE_H_

#define NVIC_TOTAL_INTERRUPT			96U
#define NVIC_REG_SIZE					32U

#define NVIC_RESERVED_INTERRUPT_1 		61U
#define NVIC_RESERVED_INTERRUPT_2 		62U
#define NVIC_RESERVED_INTERRUPT_3 		79U
#define NVIC_RESERVED_INTERRUPT_4 		80U
#define NVIC_RESERVED_INTERRUPT_5 		82U
#define NVIC_RESERVED_INTERRUPT_6 		83U
#define NVIC_RESERVED_INTERRUPT_7 		85U
#define NVIC_RESERVED_INTERRUPT_8 		86U
#define NVIC_RESERVED_INTERRUPT_9 		88U
#define NVIC_RESERVED_INTERRUPT_10 		89U
#define NVIC_RESERVED_INTERRUPT_11 		90U


#define NVIC_PRIORITY_SIZE_11 			255U

#define NVIC_PRIORITY_REG	 			4U
#define NVIC_PRIORITY_REG_SIZE 			8U

#define NVIC_GIT_ACTIVE_FLAG			1U

#endif /* NVIC_PRIVATE_H_ */
