/*
 * DMA_Private.h
 *
 *  Created on: Aug 11, 2023
 *      Author: Ziyad
 */

#ifndef DMA_PRIVATE_H_
#define DMA_PRIVATE_H_

#define  DMA_PERIPHERAL_NUM		2U
#define  DMA_STRAM_NUMs			8U

#define DMA_SET_BIT				1U

#define DMA_INTERRUPT_NUM		5U
#define DMA_STREAM_MAX			8U

#define DMA_Stream0_OFFSET     0x010UL
#define DMA_Stream1_OFFSET     0x028UL
#define DMA_Stream2_OFFSET     0x040UL
#define DMA_Stream3_OFFSET     0x058UL
#define DMA_Stream4_OFFSET     0x070UL
#define DMA_Stream5_OFFSET     0x088UL
#define DMA_Stream6_OFFSET     0x0A0UL
#define DMA_Stream7_OFFSET     0x0B8UL

#define  DMA_SxCR_CHSEL_MASK			0xF1FFFFFFUL
#define  DMA_SxCR_CHSEL_BITS_SHIFT		25U

#define  DMA_SxCR_DIR_MASK 				0xFFFFFF3FUL
#define  DMA_SxCR_DIR_BITS_SHIFT		6U

#define  DMA_SxCR_PINC_MASK 			0xFFFFFEFFUL
#define  DMA_SxCR_PINC_BITS_SHIFT		9U

#define  DMA_SxCR_MINC_MASK 			0xFFFFFDFFUL
#define  DMA_SxCR_MINC_BITS_SHIFT		10U

#define  DMA_SxCR_PSIZE_MASK 			0xFFFFE7FFUL
#define  DMA_SxCR_PSIZE_BITS_SHIFT		11U

#define  DMA_SxCR_MSIZE_MASK 			0xFFFF9FFFUL
#define  DMA_SxCR_MSIZE_BITS_SHIFT		13U

#define  DMA_SxCR_CIRC_MASK				0xFFFFFEFFUL
#define  DMA_SxCR_CIRC_BITS_SHIFT		8U

#define	 DMA_SxCR_DBM_MASK				0xFFFBFFFFUL
#define  DMA_SxCR_DBM_BITS_SHIFT		18U

#define  DMA_SxCR_PL_MASK 				0xFFFCFFFFUL
#define  DMA_SxCR_PL_BITS_SHIFT			16U

#define  DMA_SxFCR_FTH_MASK 			0xFFFFFFFCUL
#define  DMA_SxFCR_FTH_BITS_SHIFT		0U

#define  DMA_SxCR_MBURST_MASK 			0xFE7FFFFFUL
#define  DMA_SxCR_MBURST_BITS_SHIFT		23U

#define  DMA_SxCR_PBURST_MASK 			0xFF9FFFFFUL
#define  DMA_SxCR_PBURST_BITS_SHIFT		21U

#define  DMA_SxCR_INTERRUPT_MASK		0xFFFFFFE1UL
#define  DMA_SxCR_DMEIE_BITS_SHIFT		1U
#define  DMA_SxCR_TEIE_BITS_SHIFT		2U
#define  DMA_SxCR_HTIE_BITS_SHIFT		3U
#define  DMA_SxCR_TCIE_BITS_SHIFT		4U

#define  DMA_SxFCR_FEIE_INTERRUPT_MASK	0xFFFFFF7FUL
#define  DMA_SxFCR_FEIE_INTERRUPT_BIT_SHIFT		7U

#define DMA_SxFCR_DMDIS_MASK			0xFFFFFFFBUL
#define DMA_SxFCR_DMDIS_BITS_SHIFT		2U

#endif /* DMA_PRIVATE_H_ */
