/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <OSMCAL_interface.h>
#include <stdint.h>

#define SIZE_TASK_STACK		1024U
#define SIZE_SCHED_STACK	1024U

#define SRAM_START			0x20000000U
#define SIZE_SRAM			(124*1024)
#define SRAM_END			((SRAM_START)+(SIZE_SRAM))

#define T1_STACK_START		(SRAM_END)
#define T2_STACK_START		((SRAM_END) - (1*(SIZE_TASK_STACK)))
#define T3_STACK_START		((SRAM_END) - (2*(SIZE_TASK_STACK)))
#define T4_STACK_START		((SRAM_END) - (3*(SIZE_TASK_STACK)))

#define SCH_TASK_STACK		((SRAM_END) - (4*(SIZE_TASK_STACK)))

void Task1_Handler(void);
void Task2_Handler(void);
void Task3_Handler(void);
void Task4_Handler(void);

int main(void)
{
	STK_voidInit(1000);

	Stack_voidSchedulerStackInit(SCH_TASK_STACK); /*When calling this function it did Branch with link & put the LR of Task1_Handler();, so we don't need to update the value of LR. */

	Task1_Handler();

    /* Loop forever */
	for(;;);
}

void Task1_Handler(void)
{
	while (1);
}
void Task2_Handler(void)
{
	while (1);
}
void Task3_Handler(void)
{
	while (1);
}
void Task4_Handler(void)
{
	while (1);
}
